import java.util.Random;
import java.text.Normalizer;
import java.text.Normalizer.Form;
import java.text.Collator;                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              

/**
 * Esta classe tem todas as perguntas, respostas e também define as respostas correctas.
 * 
 * @author Daniel Santos
 * @version 0.1
 */
public class BancoDeDados
{
    Questoes questoes;
    
    public BancoDeDados()
    {
        iniciaAsPerguntasERespostas();
    }
    
    private void iniciaAsPerguntasERespostas()
    {
        questoes = new Questoes();
        questoes.setPergunta(1, "Qual a capital de Inglaterra?");
        questoes.setResposta(new String[]{"Londres","Madrid","Lisboa","Tóquio"});
        questoes.setRespostaCorrecta(1);
        questoes.setPergunta(1,"Qual a capital do México?");
        questoes.setResposta(new String[]{"Atenas","Brasilia","Nova Deli","Cidade do México"});
        questoes.setRespostaCorrecta(4);
        questoes.setPergunta(2, "Qual é o melhor amigo do homem?");
        questoes.setResposta(new String[]{"Gato","Veado","Cão","Gorila"});
        questoes.setRespostaCorrecta(3);
        questoes.setPergunta(2, "Destruídas pela chegada dos europeus, em que continente existiram as civilizações pré-colombianas?");
        questoes.setResposta(new String[]{"Ásia","América","África","Oceânia"});
        questoes.setRespostaCorrecta(2);
        questoes.setPergunta(3, "Qual é a capital da Tailândia?");
        questoes.setResposta(new String[]{"Bangkok","Manila","Pattaya","Phuket"});
        questoes.setRespostaCorrecta(1);
        questoes.setPergunta(1, "Qual destes países europeus não faz fronteira com nenhum dos restantes?");
        questoes.setResposta(new String[]{"Bélgica","Holanda","Polónia","França"});
        questoes.setRespostaCorrecta(3);
        questoes.setPergunta(5, "Qual naipe do baralho tem desenho de um coração?");
        questoes.setResposta(new String[]{"Ouros","Paus","Copas","Espadas"});
        questoes.setRespostaCorrecta(3);
        questoes.setPergunta(8, "Quem desenhou o Elevador de Santa Justa em Lisboa?");
        questoes.setResposta(new String[]{"Gustave Eiffel","Mesnier de Ponsard","Frank Lloyd Wright","Charles Rennie Mackintosh"});
        questoes.setRespostaCorrecta(2);
        questoes.setPergunta(1, "O kitesurf é...");
        questoes.setResposta(new String[]{"Uma ave","Uma cidade","Um desporto","Uma dança"});
        questoes.setRespostaCorrecta(3);
        questoes.setPergunta(2, "O que podemos encontrar dentro de uma ostra?");
        questoes.setResposta(new String[]{"Um caroço","Uma pérola","Um diamante","Um amendoim"});
        questoes.setRespostaCorrecta(2);
        questoes.setPergunta(3, "Qual é o primeiro nome de Shakespeare?");
        questoes.setResposta(new String[]{"Wilfred","Winston","Wayne","William"});
        questoes.setRespostaCorrecta(4);
        questoes.setPergunta(5, "Em 1987, os Xutos e Pontapés lançaram o seu terceiro álbum. Chama-se 'Circo de...'");
        questoes.setResposta(new String[]{"Acrobatas","Bestas","Leões","Feras"});
        questoes.setRespostaCorrecta(4);
        questoes.setPergunta(3, "Complete o provérbio: 'Dezembro frio, calor no...'");
        questoes.setResposta(new String[]{"Domicílio","Aconchego","Abrigo","Estio"});
        questoes.setRespostaCorrecta(4);
        questoes.setPergunta(3, "Que valor obtemos se multiplicarmos 0,1 por 5,1?");
        questoes.setResposta(new String[]{"5","0,51","51","510"});
        questoes.setRespostaCorrecta(2);
        questoes.setPergunta(15, "Como se chama a orquestra barroca sediada em Lisboa e com direção artística de Massimo Mazzeo?");
        questoes.setResposta(new String[]{"Divino Sospiro", "Ava Inferi", "Cacophony", "Vozes da Rádio"});
        questoes.setRespostaCorrecta(1);
        questoes.setPergunta(1, "Clarinete é...");
        questoes.setResposta(new String[]{"Instrumento musical","Barra de ouro","Peça de roupa","Escova de cabelo"});
        questoes.setRespostaCorrecta(1);
        questoes.setPergunta(4, "Em que século terminou a Guerra Civil Americana?");
        questoes.setResposta(new String[]{"Século XX","Século XIX","Século XVIII","Século XVII"});
        questoes.setRespostaCorrecta(2);
        questoes.setPergunta(2, "Só um destes órgãos pertence ao sistema digestivo humano. Qual?");
        questoes.setResposta(new String[]{"Pulmão","Esófago","Rim","Coração"});
        questoes.setRespostaCorrecta(2);
        questoes.setPergunta(3, "Quando é 2+2x2?");
        questoes.setResposta(new String[]{"8","4","6","2"});
        questoes.setRespostaCorrecta(3);
        questoes.setPergunta(1, "Yen é a moeda de que país?");
        questoes.setResposta(new String[]{"Austrália","Japão","Canadá","Índia"});
        questoes.setRespostaCorrecta(2);
        questoes.setPergunta(4, "No baseball, quantos strikes são permitidos ao batedor?");
        questoes.setResposta(new String[]{"Dois","Três","Um","Quatro"});
        questoes.setRespostaCorrecta(2);
        questoes.setPergunta(2, "Que autor escreveu 'Código Da Vinci'?");
        questoes.setResposta(new String[]{"Philip Roth","John Grisham","David Baldacci","Dan Brown"});
        questoes.setRespostaCorrecta(4);
        questoes.setPergunta(2, "Qual é a cor normalmente associada ao Saint Patrick's Day?");
        questoes.setResposta(new String[]{"Verde","Vermelho","Azul","Laranja"});
        questoes.setRespostaCorrecta(1);
        questoes.setPergunta(1, "Texas hold'em é uma variação de que jogo?");
        questoes.setResposta(new String[]{"Craps","Blackjack","Póquer","Roleta"});
        questoes.setRespostaCorrecta(3);
        questoes.setPergunta(4, "Quem é o apresentador do 'The Daily Show' da Comedy Central?");
        questoes.setResposta(new String[]{"Conan O'Brien","Jimmy Kimmel","Jon Stewart","Stephen Colbert"});
        questoes.setRespostaCorrecta(3);
        questoes.setPergunta(3, "Qual instrumento é que Jimi Hendrix é conhecido por tocar?");
        questoes.setResposta(new String[]{"Piano","Guitarra","Bateria","Clarinete"});
        questoes.setRespostaCorrecta(2);
        questoes.setPergunta(5, "Que serie de televisão tem como ecrã de aviso uma caveira com ossos cruzados?");
        questoes.setResposta(new String[]{"The Tom Green Show","Dr. 90210","Jackass","South Park"});
        questoes.setRespostaCorrecta(3);
        questoes.setPergunta(1, "Que vegetal dá ao Popeye força super-humana?");
        questoes.setResposta(new String[]{"Espinafre","Cenoura","Repolho","Alface"});
        questoes.setRespostaCorrecta(1);
        questoes.setPergunta(3, "Madagascar é uma ilha de que continente?");
        questoes.setResposta(new String[]{"Africa","Europa","Ásia","Ámerica do Sul"});
        questoes.setRespostaCorrecta(1);
        questoes.setPergunta(6, "Chuck D e Flavor Flav são membros de que grupo de hip-hop?");
        questoes.setResposta(new String[]{"N.W.A","De La Soul","A Tribe Called Quest","Public Enemy"});
        questoes.setRespostaCorrecta(4);
        questoes.setPergunta(2, "Sicília é uma ilha de que país?");
        questoes.setResposta(new String[]{"Itália","Malásia","Filipinas","Austrália"});
        questoes.setRespostaCorrecta(1);
        questoes.setPergunta(2, "Qual é o primeiro nome da mulher do antigo presidente dos Estados Unidos Bill Clinton?");
        questoes.setResposta(new String[]{"Nancy","Hillary","Laura","Bárbara"});
        questoes.setRespostaCorrecta(2);
        questoes.setPergunta(3, "Quantos anos tem um mandato de um Presidente da República eleito?");
        questoes.setResposta(new String[]{"Dois","Dez","Quatro","Cinco"});
        questoes.setRespostaCorrecta(4);
        questoes.setPergunta(2, "Qual é a cor principal de um sinal de STOP?");
        questoes.setResposta(new String[]{"Roxo","Azul","Verde","Vermelho"});
        questoes.setRespostaCorrecta(4);
        questoes.setPergunta(7, "Por qual membro dos Beatles é que Yoko Ono casou?");
        questoes.setResposta(new String[]{"Paul McCartney","John Lennon","Ringo Starr","George Harrison"});
        questoes.setRespostaCorrecta(2);
        questoes.setPergunta(3, "Quem escreveu a sequela 'Senhor dos Anéis'?");
        questoes.setResposta(new String[]{"J.R.R. Tolkien","Frank Herbert","J.K. Rowling","J.D. Salinger"});
        questoes.setRespostaCorrecta(1);
        questoes.setPergunta(1, "Qual expressão significa uma nota chumbada?");
        questoes.setResposta(new String[]{"Bom","Insatisfaz","Satisfaz","Muito Bom"});
        questoes.setRespostaCorrecta(2);
        questoes.setPergunta(1, "Quantos aneis de cores aparece na bandeira Olímpica?");
        questoes.setResposta(new String[]{"Quatro","Cinco","Sete","Oito"});
        questoes.setRespostaCorrecta(2);
        questoes.setPergunta(2, "De qual banda pop pertenceu Justin Timberlake?");
        questoes.setResposta(new String[]{"98 Degrees","*NSYNC","The Backstreet Boys","B2K"});
        questoes.setRespostaCorrecta(2);
        questoes.setPergunta(3, "Quem chamarias para concertar a canalização?");
        questoes.setResposta(new String[]{"Serralheiro","Electricista","Canalizador","Mecânico"});
        questoes.setRespostaCorrecta(3);
        questoes.setPergunta(2, "Que actor intrepeta 'Rocky Balboa' nas séries 'Rocky'?");
        questoes.setResposta(new String[]{"Hulk Hogan","Val Kilmer","Sylvester Stallone","Patrick Swayze"});
        questoes.setRespostaCorrecta(3);
        questoes.setPergunta(4, "Qual dos seguintes não é um queijo?");
        questoes.setResposta(new String[]{"Manicotti","Cheddar","Feta","Ricotta"});
        questoes.setRespostaCorrecta(1);
        questoes.setPergunta(1, "De que série de televisão pertencem os agentes do FBI Fox Mulder e Dana Scully?");
        questoes.setResposta(new String[]{"Lost","Friends","24","Ficheiros Secretos"});
        questoes.setRespostaCorrecta(4);
        questoes.setPergunta(3, "Que desporto é jogado num campo em forma de diamante?");
        questoes.setResposta(new String[]{"Baseball","Hóquei em Patins","Voleibol","Basquete"});
        questoes.setRespostaCorrecta(1);
        questoes.setPergunta(4, "Alguém que esteja a navegar em águas do Mar Vermelho nunca poderá parar...");
        questoes.setResposta(new String[]{"no Sudão","no Egipto","na Arábia Saudita","na China"});
        questoes.setRespostaCorrecta(4);
        questoes.setPergunta(4, "Como se denonima um triângulo que tenha os lados todos iguais menos um?");
        questoes.setResposta(new String[]{"Isósceles","Escaleno","Agudo","Equilátero"});
        questoes.setRespostaCorrecta(1);
        questoes.setPergunta(4, "Em 1941, surgiu em Lisboa a revista...");
        questoes.setResposta(new String[]{"TV Guia","Panorama","Grande","Tintin"});
        questoes.setRespostaCorrecta(2);
        questoes.setPergunta(4, "Qual destes animais não é um roedor?");
        questoes.setResposta(new String[]{"Impala","Castor","Coelho","Esquilo"});
        questoes.setRespostaCorrecta(1);
        questoes.setPergunta(4, "Que cidade tem a Praça Vermelha mais famosa do mundo?");
        questoes.setResposta(new String[]{"Roma","Moscovo","Veneza","Kiev"});
        questoes.setRespostaCorrecta(2);
        questoes.setPergunta(7, "Quem criou a série norte-americana Supernatural?");
        questoes.setResposta(new String[]{"Chuck Lorre","Eric Kripke","Brian Johnson","Adam Campbell"});
        questoes.setRespostaCorrecta(2);
        questoes.setPergunta(10, "Qual o protagonista da série japonesa do One Piece?");
        questoes.setResposta(new String[]{"Son Goku","Kurosaki Ichigo","Natsu Dragneel","Monkey D. Luffy"});
        questoes.setRespostaCorrecta(4);
        questoes.setPergunta(9, "Segundo o Corão, qual o número máximo de mulheres com quem um muçulmano pode casar?");
        questoes.setResposta(new String[]{"Quatro","Cinco","Sete","Doze"});
        questoes.setRespostaCorrecta(1);
        questoes.setPergunta(1, "Como se chamava o cavalo de D. Quixote?");
        questoes.setResposta(new String[]{"Silver","Rocinante","Lassie","Jolly Jumper"});
        questoes.setRespostaCorrecta(2);
        questoes.setPergunta(3, "Onde se situa o Cabo Canaveral, conhecido pelos lançamentos espaciais norte-americanos?");
        questoes.setResposta(new String[]{"Texas","Florida","Califórnia","Massachussets"});
        questoes.setRespostaCorrecta(2);
        questoes.setPergunta(4, "Em 'Amor de Perdição' Camilo Castelo Branco narra a história de amor de que casal?");
        questoes.setResposta(new String[]{"Dante e Beatriz","Carlos e Maria Eduarda","Simão e Teresa","Tristão e Isolda"});
        questoes.setRespostaCorrecta(3);
        questoes.setPergunta(5, "Após a Revolução Francesa de 1789, já em 1793, o que aconteceu ao deposto rei Luís XVI?");
        questoes.setResposta(new String[]{"Exílio","Recoroação","Decapitação","Jubilação"});
        questoes.setRespostaCorrecta(3);
        questoes.setPergunta(6, "No caso Watergate, por que nome ficou conhecida a fonte anónima que informava o Washington Post?");
        questoes.setResposta(new String[]{"Papo de Anjo","Garganta Funda","Lapsus Linguae","Bica Aberta"});
        questoes.setRespostaCorrecta(2);
        questoes.setPergunta(7, "A que planeta apontou Galileu o seu telescópio, descobrindo as primeiras luas extraterrestres?");
        questoes.setResposta(new String[]{"Mercúrio","Urano","Plutão","Júpiter"});
        questoes.setRespostaCorrecta(4);
        questoes.setPergunta(8, "Com qual dos seguintes países a Áustria não faz fronteira?");
        questoes.setResposta(new String[]{"República Checa","Eslovénia","Eslováquia","Croácia"});
        questoes.setRespostaCorrecta(4);
        questoes.setPergunta(9, "Quem venceu o Campeonato Mundial de Ralis de 2013?");
        questoes.setResposta(new String[]{"Mikko Hirvonen","Sébastien Ogier","Jari-Matti Latvala","Petter Solberg"});
        questoes.setRespostaCorrecta(2);
        questoes.setPergunta(10, "Que artista pop art é o autor da pintura 'Whaam'?");
        questoes.setResposta(new String[]{"Tom Wesselmann","Roy Lichtenstein","Paula Rego","Amedeo Modigliani"});
        questoes.setRespostaCorrecta(2);
        questoes.setPergunta(11, "O povo Islandês decidiu em plebiscito, em 1944, a independência do seu país, separando-se...");
        questoes.setResposta(new String[]{"da Irlanda","da Dinamarca","da Gronelândia","da Suécia"});
        questoes.setRespostaCorrecta(2);
        questoes.setPergunta(12, "Antes de vencer o Open da Malásia de 2013, João Sousa derrotou que tenista nos quartos de final?");
        questoes.setResposta(new String[]{"Juan Martin del Potro","David Ferrer","Roger Federer","Andy Murray"});
        questoes.setRespostaCorrecta(2);
        questoes.setPergunta(13, "Uma destas músicas do disco de Carminho tem letra de Vasco Graça Moura. Qual?");
        questoes.setResposta(new String[]{"Talvez","Meu Namorado","Fado Adeus","Ruas"});
        questoes.setRespostaCorrecta(1);
        questoes.setPergunta(14, "Quem pintou o tríptico 'Três Estudos de Lucian Freud', obra vendida em leilão em novembro de 2013?");
        questoes.setResposta(new String[]{"Piet Mondrian","Wassily Kandinsky","Victor Vasarely","Francis Bacon"});
        questoes.setRespostaCorrecta(4);
        questoes.setPergunta(4, "O violino é um instrumento de...");
        questoes.setResposta(new String[]{"Teclas","Percurssão","Cordas","Sopro"});
        questoes.setRespostaCorrecta(3);
        questoes.setPergunta(5, "Como se classifica o morcego?");
        questoes.setResposta(new String[]{"Mamífero","Réptil","Insecto","Ave"});
        questoes.setRespostaCorrecta(1);
        questoes.setPergunta(2, "Como se chama a namorada do Rato Mickey?");
        questoes.setResposta(new String[]{"Minie","Mafalda","Margarida","Mónica"});
        questoes.setRespostaCorrecta(1);
        questoes.setPergunta(3, "Crawl é...");
        questoes.setResposta(new String[]{"Dança","Género Musical","Estilo de Natação","Instrumento Agrícola"});
        questoes.setRespostaCorrecta(3);
        questoes.setPergunta(1, "Qual destes Jacques foi presidente da Comissão Europeia?");
        questoes.setResposta(new String[]{"Cousteau","Tati","Brel","Delors"});
        questoes.setRespostaCorrecta(4);
        questoes.setPergunta(2, "A reprodução das plantas com flor é feita muitas vezes pelo transporte de pólen, isto é...");
        questoes.setResposta(new String[]{"Pelo enxerto","Pela polinização","Pela transmutação","Pela fotossíntese"});
        questoes.setRespostaCorrecta(2);
        questoes.setPergunta(3, "Qual das seguintes equipas da Premier League inglesa está sediada em Londres?");
        questoes.setResposta(new String[]{"Manchester United","Liverpool","Newcastle","Chelsea"});
        questoes.setRespostaCorrecta(4);
        questoes.setPergunta(4, "Qual destes planetas do Sistema Solar é maior do que a Terra?");
        questoes.setResposta(new String[]{"Vénus","Mercúrio","Marte","Saturno"});
        questoes.setRespostaCorrecta(4);
        questoes.setPergunta(5, "Polémico desde que foi anunciado, que díptico cinematográfico Lars von Trier assinou em 2013?");
        questoes.setResposta(new String[]{"Melancolia","Ninfomaníaca","Dogville","Dancer In The Dark"});
        questoes.setRespostaCorrecta(2);
        questoes.setPergunta(1, "A estilista Mary Quant é responsável por popularizar o uso de que peça de vestuário?");
        questoes.setResposta(new String[]{"Chapéu","Luva","Minissaia","Cachecol"});
        questoes.setRespostaCorrecta(3);
        questoes.setPergunta(2, "De que mitologia são originários os atuais nomes dos planetas do Sistema Solar?");
        questoes.setResposta(new String[]{"Maia","Egípcia","Persa","Greco-romana"});
        questoes.setRespostaCorrecta(4);
        questoes.setPergunta(3, "Qual destes êxitos é de Michael Jackson?");
        questoes.setResposta(new String[]{"Black or White","Give it Away","Mysterious Ways","I Will Always Love You"});
        questoes.setRespostaCorrecta(1);
        questoes.setPergunta(4, "Qual dos seguintes é um sinónimo do verbo 'anuir'?");
        questoes.setResposta(new String[]{"Esquecer","Comprar","Aprovar","Aniquilar"});
        questoes.setRespostaCorrecta(3);
        questoes.setPergunta(5, "Quem substituiu Sir Alex Ferguson à frente do Manchester United, em 2013?");
        questoes.setResposta(new String[]{"José Mourinho","David Moyes","Carlo Ancelotti","André Villas-Boas"});
        questoes.setRespostaCorrecta(2);
        questoes.setPergunta(6, "'O Êxtase de Santa Teresa' é uma escultura exemplo de que período artístico?");
        questoes.setResposta(new String[]{"Barroco","Simbolismo","Surrealismo","Cubismo"});
        questoes.setRespostaCorrecta(1);
        questoes.setPergunta(7, "Em qual destes planetas existe uma Grande Mancha Vermelha?");
        questoes.setResposta(new String[]{"Júpiter","Mercúrio","Neptuno","Vénus"});
        questoes.setRespostaCorrecta(1);
        questoes.setPergunta(8, "Quantos eram os degraus no famoso thriller de 1935 realizado por Hitchcock?");
        questoes.setResposta(new String[]{"2","20","39","66"});
        questoes.setRespostaCorrecta(3);
        questoes.setPergunta(9, "'Carnaval de Arlequim' e 'Cão a Ladrar à Lua' são obras de que pintor catalão?");
        questoes.setResposta(new String[]{"Salvador Dalí","Joan Miró","Antoni Tàpies","Antoni Gaudí"});
        questoes.setRespostaCorrecta(2);
        questoes.setPergunta(10, "O oficial da Marinha Pinkerton e o sônsul Sharpless são personagens de que ópera?");
        questoes.setResposta(new String[]{"Aida","Tristão e Isolda","Carmen","Madama Butterfly"});
        questoes.setRespostaCorrecta(4);
        questoes.setPergunta(1, "Qual destes músicos associamos à guitarra eléctrica?");
        questoes.setResposta(new String[]{"Ringo Starr","Jerry Lee Lewis","Miles Davis","Jimi Hendrix"});
        questoes.setRespostaCorrecta(4);
        questoes.setPergunta(2, "Qual destes lugares imaginários encontramos descrito em 'Os Lusíadas'?");
        questoes.setResposta(new String[]{"Terra do Nunca","País das Maravilhas","Ilha dos Amores","Terra Média"});
        questoes.setRespostaCorrecta(3);
        questoes.setPergunta(3, "O que significa o verbo transitivo 'almejar'?");
        questoes.setResposta(new String[]{"Alvejar","Desejar","Construir","Antecipar"});
        questoes.setRespostaCorrecta(2);
        questoes.setPergunta(4, "Em qual dos seguintes clássicos James Dean e Elizabeth Taylor contracenaram?");
        questoes.setResposta(new String[]{"Bonnie e Clyde","Janela Indiscreta","O Gigante","Rio Grande"});
        questoes.setRespostaCorrecta(3);
        questoes.setPergunta(8, "Qual é a banda musical de Armando Teixeira?");
        questoes.setResposta(new String[]{"Balla","Tambor","Pedra","Bola"});
        questoes.setRespostaCorrecta(1);
        questoes.setPergunta(9, "Quantas ilhas formam a Indonésia?");
        questoes.setResposta(new String[]{"4","12","253","Mais de 17.500"});
        questoes.setRespostaCorrecta(4);
        questoes.setPergunta(1, "De miúdos a graúdos, todos sabem ou deviam saber:\n'o prometido é...'");
        questoes.setResposta(new String[]{"De vidro","Devido","Dividido","Divino"});
        questoes.setRespostaCorrecta(2);
        questoes.setPergunta(2, "Qual das seguintes substâncias é frequentemente usada nas baterias de 'smartphones'?");
        questoes.setResposta(new String[]{"Vidro","Lítio","Madeira","Calcário"});
        questoes.setRespostaCorrecta(2);
        questoes.setPergunta(3, "Que animais ladeiam a escadaria de acesso à Assembleia da República, em Lisboa?");
        questoes.setResposta(new String[]{"Cavalos","Dragões","Leões","Girafas"});
        questoes.setRespostaCorrecta(3);
        questoes.setPergunta(5, "Quem interpreta o tema 'Boom sem Parar'?");
        questoes.setResposta(new String[]{"Bombocas","Ana Malhoa","Santamaria","Kátia Aveiro"});
        questoes.setRespostaCorrecta(4);
        questoes.setPergunta(6, "Quem escreveu 'O Conde de Monte Cristo'?");
        questoes.setResposta(new String[]{"Marguerite Duras","Alexandre Dumas","Charles Darwin","Roald Dahl"});
        questoes.setRespostaCorrecta(2);
        questoes.setPergunta(7, "Qual é a capital do Canadá?");
        questoes.setResposta(new String[]{"Otava","Vancouver","Toronto","Montreal"});
        questoes.setRespostaCorrecta(1);
        questoes.setPergunta(8, "Quem realizou 'Wolverine', o filme sobre uma das personagens do universo 'X-Men'?");
        questoes.setResposta(new String[]{"Sam Mendes","Christopher Nolan","James Mangold","Guy Ritchie"});
        questoes.setRespostaCorrecta(3);
        questoes.setPergunta(1, "No filme 'World War Z', o ator Brad Pitt é constantemente perseguido por:");
        questoes.setResposta(new String[]{"Zombies","Cobradores de impostos","Mulheres","Vendedores de gelados"});
        questoes.setRespostaCorrecta(1);
        questoes.setPergunta(2, "Um destes veículos não voa por propulsão própria. Qual?");
        questoes.setResposta(new String[]{"Avião","Helicóptero","Foguetão","Tanque"});
        questoes.setRespostaCorrecta(4);
        questoes.setPergunta(3, "Qual dos polígnos é sinónimo de aparelho de ginástica, de osso da mão e de músculo do tronco?");
        questoes.setResposta(new String[]{"Losango","Trapézio","Hexágono","Triângulo"});
        questoes.setRespostaCorrecta(2);
        questoes.setPergunta(4, "Antes de se tornar ator e cantor, David, filho de Tony Carreira, jogou num clube de futebol. Qual?");
        questoes.setResposta(new String[]{"Sporting","Benfica","Porto","Académica"});
        questoes.setRespostaCorrecta(1);
        questoes.setPergunta(1, "Qual destas hipóteses é um doce típico de Sintra?");
        questoes.setResposta(new String[]{"Almofada","Travesseiro","Édredon","Colchão"});
        questoes.setRespostaCorrecta(2);
        questoes.setPergunta(2, "Qual o nome do deus egípcio do Sol?");
        questoes.setResposta(new String[]{"Dó","Rá","Mi","Fá"});
        questoes.setRespostaCorrecta(2);
        questoes.setPergunta(3, "Qual destes navegadores descobriu o caminho marítimo para a Índia?");
        questoes.setResposta(new String[]{"Fernão de Magalhães","Diogo Cão","Vasco da Gama","Pedro Álvares Cabral"});
        questoes.setRespostaCorrecta(3);
        questoes.setPergunta(4, "Rio Tinto é uma freguesia de que concelho?");
        questoes.setResposta(new String[]{"Torres Vedras","Guimarães","Gondomar","Vidigueira"});
        questoes.setRespostaCorrecta(3);
        questoes.setPergunta(5, "Que atriz protagoniza 'E Depois do Adeus', a série da RTP?");
        questoes.setResposta(new String[]{"Catarina Furtado","Rita Blanco","Ana Nave","Maria de Medeiros"});
        questoes.setRespostaCorrecta(3);
        questoes.setPergunta(6, "Quem falava na obra de Nietzsche?");
        questoes.setResposta(new String[]{"Zaratustra","Zapruder","Zoetrope","Zenão"});
        questoes.setRespostaCorrecta(1);
        questoes.setPergunta(7, "Onde jogava Neymar antes de ingressar no Barcelona?");
        questoes.setResposta(new String[]{"Palmeiras","Botafogo","Boca Juniors","Santos"});
        questoes.setRespostaCorrecta(4);
        questoes.setPergunta(1, "Destas respostas, qual é a mais habitual nas decorações de Natal?");
        questoes.setResposta(new String[]{"Coelhos","Serpentinas","Árvore com luzes","Chapéu de sol"});
        questoes.setRespostaCorrecta(3);
        questoes.setPergunta(2, "Que antónimo escolherias para mudar o título do livro 'O Patinho Feio'?");
        questoes.setResposta(new String[]{"Zangado","Bonito","Simpático","Escuro"});
        questoes.setRespostaCorrecta(2);
        questoes.setPergunta(3, "Completa o verso da canção de Natal: 'Olhei para o céu, estava...'");
        questoes.setResposta(new String[]{"Apagado","Povoado","Azulado","Estrelado"});
        questoes.setRespostaCorrecta(4);
        questoes.setPergunta(4, "O que é a Assembleia da República?");
        questoes.setResposta(new String[]{"Casa do Presidente da República","Quartel militar","Onde se fazem as leis","Onde vamos para falar"});
        questoes.setRespostaCorrecta(3);
        questoes.setPergunta(5, "Como se diz 'boa sorte' em inglês?");
        questoes.setResposta(new String[]{"I love you","Good morning","Good luck","Welcome"});
        questoes.setRespostaCorrecta(3);
        questoes.setPergunta(11, "Que rio atravessa as Cataratas Vitória?");
        questoes.setResposta(new String[]{"Rio Nilo","Rio Congo","Rio Limpopo","Rio Zambeze"});
        questoes.setRespostaCorrecta(4);
        questoes.setPergunta(11, "Que jornalista deu a noticia do inicio da Guerra do Golfo em 1991, no noticiário '24 Horas' da RTP?");
        questoes.setResposta(new String[]{"José Alberto Carvalho","Carlos Fino","José Rodrigues dos Santos","Henrique Garcia"});
        questoes.setRespostaCorrecta(3);
        questoes.setPergunta(12, "No jogo 'League of Legends', o que é preciso destruir da equipa adversária?");
        questoes.setResposta(new String[]{"O Nexus","O Focus","O Dux","O Maximus"});
        questoes.setRespostaCorrecta(1);
        questoes.setPergunta(1, "Os termos 'match point', 'tie-break', 'deuce' e 'passing shot' costumam ouvir-se em que modalidade?");
        questoes.setResposta(new String[]{"Futebol","Andebol","Bilhar","Ténis"});
        questoes.setRespostaCorrecta(4);
        questoes.setPergunta(2, "Obrigatórias nos subsolos urbanos, a que se destinam as redes de drenagem pluviais?");
        questoes.setResposta(new String[]{"Esgotos domésticos","Águas das chuvas","Esgotos industriais","Abastecimento doméstico"});
        questoes.setRespostaCorrecta(2);
        questoes.setPergunta(3, "Em que área se notabiliza a norte-americana Annie Leibovitz?");
        questoes.setResposta(new String[]{"Fotografia","Arquitetura","Escultura","Dança"});
        questoes.setRespostaCorrecta(1);
        questoes.setPergunta(4, "Em que país do Norte de África fica situada a cidade de Agadir?");
        questoes.setResposta(new String[]{"Marrocos","Argélia","Tunísia","Egito"});
        questoes.setRespostaCorrecta(1);
        questoes.setPergunta(5, "Com onze estatuetas, qual destes filmes está entre os três mais premiados da história dos Óscares?");
        questoes.setResposta(new String[]{"Argo","Imperdoável","Titanic","O Artista"});
        questoes.setRespostaCorrecta(3);
        questoes.setPergunta(6, "Qual dos seguintes elementos da Tabela Periódica foi descoberto apenas no século XX?");
        questoes.setResposta(new String[]{"Ouro","Plutónio","Cobre","Platina"});
        questoes.setRespostaCorrecta(2);
        questoes.setPergunta(7, "Qual destes temas não é dos Blondie?");
        questoes.setResposta(new String[]{"Psycho Killer","Heart Of Glass","Call Me","One Way Or Another"});
        questoes.setRespostaCorrecta(1);
        questoes.setPergunta(8, "Em que século passou o Meridiano de Greenwich a ser determinativo dos fusos horários?");
        questoes.setResposta(new String[]{"X","XIV","XVI","XIX"});
        questoes.setRespostaCorrecta(4);
        questoes.setPergunta(9, "Sobre qual das seguintes cores trabalhou extensivamente o pintor Yves Klein?");
        questoes.setResposta(new String[]{"Castanho","Azul","Verde","Amarelo"});
        questoes.setRespostaCorrecta(2);
        questoes.setPergunta(10, "Qual das atrizes entra no filme 'Paris, Texas', de Wim Wenders?");
        questoes.setResposta(new String[]{"Michelle Pfeiffer","Nastassja Kinski","Rosanna Arquette","Meg Ryan"});
        questoes.setRespostaCorrecta(2);
        questoes.setPergunta(11, "Em que ano do século XX a cidade de Brasília foi inaugurada como capital do Brasil?");
        questoes.setResposta(new String[]{"1957","1959","1960","1987"});
        questoes.setRespostaCorrecta(3);
        questoes.setPergunta(1, "A aranha mediterrânica é vulgarmente conhecida por que outro nome?");
        questoes.setResposta(new String[]{"Viúva-negra","Peixe-aranha","Flor-de-viúva","Viúva-alegre"});
        questoes.setRespostaCorrecta(1);
        questoes.setPergunta(5, "Em qual dos Emirados Árabes Unidos fica o edifício mais alta do mundo?");
        questoes.setResposta(new String[]{"Sharjah","Dubai","Abu Dhabi","Fujairah"});
        questoes.setRespostaCorrecta(2);
        questoes.setPergunta(4, "Qual destes planetas não possui nenhuma lua?");
        questoes.setResposta(new String[]{"Saturno","Terra","Júpiter","Vénus"});
        questoes.setRespostaCorrecta(4);
        questoes.setPergunta(1, "Qual dos seguintes é o nome da abelha mais famosa do mundo dos desenhos animados?");
        questoes.setResposta(new String[]{"Mónica","Maia","Minnie","Mafalda"});
        questoes.setRespostaCorrecta(2);
        questoes.setPergunta(2, "Qual destes desportos não é praticado nas aulas de Educação Física no ensino público em Portugal?");
        questoes.setResposta(new String[]{"Futebol","Basquetebol","Andebol","Críquete"});
        questoes.setRespostaCorrecta(4);
        questoes.setPergunta(3, "O filme 'Maléfica' conta a história da vilã de um conhecido conto infantil. Qual?");
        questoes.setResposta(new String[]{"A Bela Adormecida","Cinderela","Dumbo","Pinóquio"});
        questoes.setRespostaCorrecta(1);
        questoes.setPergunta(4, "Qual destas palavras é um advérbio de modo?");
        questoes.setResposta(new String[]{"Forma","Obviamente","Atrasar","Para"});
        questoes.setRespostaCorrecta(2);
        questoes.setPergunta(5, "Que político português esteve à frente da Comissão Europeia entre 2004 e 2014?");
        questoes.setResposta(new String[]{"Ramalho Eanes","António Guterres","Durão Barroso","Jorge Sampaio"});
        questoes.setRespostaCorrecta(3);
        questoes.setPergunta(6, "Qual dos seguintes não é um 'vloguer' português?");
        questoes.setResposta(new String[]{"Zoella","Diogo Sena","Peperan","Nurb"});
        questoes.setRespostaCorrecta(1);
        questoes.setPergunta(8, "No conto 'Vicente', de Miguel Torga, o pássaro protagonista abandona a Arca de Noé. Que tipo de ave é?");
        questoes.setResposta(new String[]{"Melro","Águia","Gaivota","Corvo"});
        questoes.setRespostaCorrecta(4);
        questoes.setPergunta(9, "Em que local podemos visitar o túmulo de D. Pedro I?");
        questoes.setResposta(new String[]{"Casa dos Bicos","Mosteiro de Alcobaça","Mosteiro da Batalha","Mosteiro dos Jerónimos"});
        questoes.setRespostaCorrecta(2);
        questoes.setPergunta(10, "O resultado de qualquer potência de base diferente de zero e expoente igual a zero é:");
        questoes.setResposta(new String[]{"-1","0","1","2"});
        questoes.setRespostaCorrecta(3);
        questoes.setPergunta(11, "Que presidente norte-americano autorizou o desenvolvimento da primeira bomba nuclear ou de hidrogénio, em 1950?");
        questoes.setResposta(new String[]{"Franklin Roosevelt","Lyndon Johnson","Richard Nixon","Harry Truman"});
        questoes.setRespostaCorrecta(4);
        questoes.setPergunta(12, "A escala de Saffir-Simpson mede a intensidade de...");
        questoes.setResposta(new String[]{"Terramotos","Tsunamis","Furacões","Relâmpagos"});
        questoes.setRespostaCorrecta(3);
        questoes.setPergunta(1, "Que nome se dá ao local onde desagua um rio?");
        questoes.setResposta(new String[]{"Margem","Leito","Nascente","Foz"});
        questoes.setRespostaCorrecta(4);
        questoes.setPergunta(2, "Em que ilha dos Açores fica situada a cidade de Ponta Delgada?");
        questoes.setResposta(new String[]{"São Jorge","São Miguel","Terceira","Graciosa"});
        questoes.setRespostaCorrecta(2);
        questoes.setPergunta(3, "Qual destas palavras é considerada uma preposição?");
        questoes.setResposta(new String[]{"Em","Aí","Uma","Qual"});
        questoes.setRespostaCorrecta(1);
        questoes.setPergunta(5, "Antes de sua carreira a solo, Beyoncé Knowles integrava um grupo feminino. Qual?");
        questoes.setResposta(new String[]{"The Ronettes","Destiny's Child","Sugababes","The Bangles"});
        questoes.setRespostaCorrecta(2);
        questoes.setPergunta(6, "Qual dos seguintes verbos está no infinitivo impessoal?");
        questoes.setResposta(new String[]{"Estava","Existo","Sendo","Haver"});
        questoes.setRespostaCorrecta(4);
        questoes.setPergunta(7, "Existem planetas visíveis a olho nu a partir da Terra. Qual destes não se consegue ver sem telescópio?");
        questoes.setResposta(new String[]{"Júpiter","Neptuno","Marte","Vénus"});
        questoes.setRespostaCorrecta(2);
        questoes.setPergunta(8, "Além da Estrela e da Lousã, qual das seguintes serras portuguesas pertence à Cordilheira Central?");
        questoes.setResposta(new String[]{"Açor","Gerês","Monsanto","Arrábida"});
        questoes.setRespostaCorrecta(1);
        questoes.setPergunta(9, "Que personagem lusitana é descrita por João Aguiar no seu livro 'A Voz dos Deuses', de 1984?");
        questoes.setResposta(new String[]{"Júlio César","Viriato","Átila","Caio Vetílio"});
        questoes.setRespostaCorrecta(2);
        questoes.setPergunta(10, "Mozart compôs várias óperas. Qual destas é da sua autoria?");
        questoes.setResposta(new String[]{"Tosca","La Bohème","Madama Butterfly","As Bodas de Fígaro"});
        questoes.setRespostaCorrecta(4);
        questoes.setPergunta(8, "De qual destas bandas já fez parte o virtuoso guitarrista norte-americano Steve Vai?");
        questoes.setResposta(new String[]{"Metallica","Whitesnake","Europe","Scorpions"});
        questoes.setRespostaCorrecta(2);
        questoes.setPergunta(13, "O Prémio Nobel da Literatura é atribuído desde 1901.\nQual destes escritores não o recebeu?");
        questoes.setResposta(new String[]{"Mario Vargas Llosa","José Saramago","William Faulkner","Paul Auster"});
        questoes.setRespostaCorrecta(4);
        questoes.setPergunta(4, "Que sigla designa habitualmente o comandante dos três ramos das forças armadasportuguesas?");
        questoes.setResposta(new String[]{"CEME","CEMGFA","CEMFA","CEMA"});
        questoes.setRespostaCorrecta(2);
        questoes.setPergunta(3, "Qual das seguintes hipóteses é um estilo musical criado na viragem para o século XX no sul dos EUA?");
        questoes.setResposta(new String[]{"Reds","Greens","Blacks","Blues"});
        questoes.setRespostaCorrecta(4);
        questoes.setPergunta(1, "O famoso logótipo dos The Rolling Stones é composto por lábios vermelhos e...");
        questoes.setResposta(new String[]{"Uma língua de fora","Uma fileira de dentes","Um 'piercing' labial","Um bigode"});
        questoes.setRespostaCorrecta(1);
        questoes.setPergunta(2, "Na numeração romana, que número é representado pelo símbolo L?");
        questoes.setResposta(new String[]{"10","50","100","1000"});
        questoes.setRespostaCorrecta(2);
        questoes.setPergunta(3, "Estocolmo é a capital de que país da Europa?");
        questoes.setResposta(new String[]{"Noruega","Suécia","Suíça","Dinamarca"});
        questoes.setRespostaCorrecta(2);
        questoes.setPergunta(4, "Em qual das seguintes áreas se notabilizou Aristides de Sousa Mendes?");
        questoes.setResposta(new String[]{"Pintura","Poesia","Diplomacia","Arquitetura"});
        questoes.setRespostaCorrecta(3);
        questoes.setPergunta(5, "Um destes filmes não foi realizado por Quentin Tarantino. Qual?");
        questoes.setResposta(new String[]{"Pulp Fiction","Magnólia","Django Libertado","Cães Danados"});
        questoes.setRespostaCorrecta(2);
        questoes.setPergunta(6, "Quem escreveu 'Jerusalém'?");
        questoes.setResposta(new String[]{"José Luís Peixoto","José Cardoso Pires","José Saramago","Gonçalo M. Tavares"});
        questoes.setRespostaCorrecta(4);
        questoes.setPergunta(7, "Dave Grohl, ex-baterista dos Nirvana, é o atual vocalista de que banda?");
        questoes.setResposta(new String[]{"Foo Fighters","Queens of the Stone Age","Pearl Jam","Soundgarden"});
        questoes.setRespostaCorrecta(1);
        questoes.setPergunta(1, "Que atleta português venceu a prova de Maratona nos Jogos Olímpicos de Los Angeles em 1984?");
        questoes.setResposta(new String[]{"António Leitão","Carlos Lopes","Rui Silva","Fernando Mamede"});
        questoes.setRespostaCorrecta(2);
        //questoes.setPergunta(12, "Sicília é uma ilha de que país?");
        //questoes.setResposta(new String[]{"Itália","Malásia","Filipinas","Austrália"});
        //questoes.setRespostaCorrecta(1);
    }
    
    public Questoes get() { return questoes; }
    
    public void stats()
    {
        for(int i=1; i<=15; i++) {
            System.out.println((i) + ": " + questoes.getSize(i));
        }
    }
    
    public String haRepetidos()
    {
        final Collator instance = Collator.getInstance();
        instance.setStrength(Collator.NO_DECOMPOSITION);
        for(int nivel=1; nivel <= 15; nivel++) {
            for(int num=0; num < questoes.getSize(nivel);num++) {
                String pergunta = questoes.getPergunta(nivel,num).toLowerCase();
                for(int cmpNivel=nivel; cmpNivel <= 15; cmpNivel++) {
                    for(int cmpNum=0; cmpNum < questoes.getSize(cmpNivel); cmpNum++) {
                        if(nivel == cmpNivel && cmpNum == 0) {
                            cmpNum = num;
                            continue;
                        }
                        String pergunta2 = questoes.getPergunta(cmpNivel,cmpNum).toLowerCase();
                        if(instance.compare(pergunta,pergunta2) == 0)
                            return questoes.getPergunta(cmpNivel,cmpNum);
                    }
                }
            }
        }
        return null;
    }
    
    private String removeAccents(String string)
    {
        return Normalizer.normalize(string, Form.NFD)
            .replaceAll("\\p{InCombiningDiacriticalMarks}+", "");
    }
}
